#!/usr/bin/env bash
# server are the place of software generating and serving HTML pages
#installing nginx on the web-01

apt-get update -y
apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
sh -c 'echo "Hello world!" > /var/www/html/index.html'
service nginx restart
