#!/usr/bin/env bash
# Installs nginx web server and configures it

apt-get -y update
apt-get -y install nginx
ufw allow "Nginx HTTP"
echo "Hello World!" >/var/www/html/index.nginx-debian.html
service nginx restart
