#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page
STRING="\n\tlocation /redirect_me {\n\t\treturn 301 https://youtube.com;\n\t}\n"
FILE="/etc/nginx/sites-available/default"

apt-get -y update
apt-get -y install nginx
ufw allow "Nginx HTTP"
echo "Hello World!" >/var/www/html/index.nginx-debian.html
sed -i "37i\ $STRING" "$FILE"
service nginx restart
