#!/usr/bin/env bash
# server are the place of software generating and serving HTML pages
#installing nginx on the web-01

apt-get update -y
apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
sh -c 'echo "Hello world!" > /var/www/html/index.html'
sudo touch /var/www/html/404.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/@yabbby permanent;' /etc/nginx/sites-available/default
sed -i '/listen 80 default_server/a error_page 404 /404.html;'/etc/nginx/sites-available/default
service nginx restart
