#!/usr/bin/env bash
# installs and configures HAProxy

sudo apt install -y --no-install-recommends software-properties-common
sudo apt update -y
sudo apt install -y haproxy

CONFIG="\
frontend http_front
	bind *:80
	mode http
	default_backend http_back

backend http_back
	balance roundrobin
	server 417172-web-01 54.236.53.2:80 check
	server 417172-web-02 34.204.82.22:80 check
"

sudo echo "$CONFIG" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
