#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
i=1
while [ "$i" -le 20 ]; do
	case "$i" in
	4)
		printf "%i\nbad luck from China\n" "$i"
		;;
	9)
		printf "%i\nbad luck from Japan\n" "$i"
		;;
	17)
		printf "%i\nbad luck from Italy\n" "$i"
		;;
	*)
		echo $i
		;;
	esac
	((i++))
done
